apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: ml-dev
    server: https://kubernetes.default.svc
  source:
    repoURL: "${REPO_URL}"
    targetRevision: "${REVISION}"
    path: charts/jupyterhub
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Replace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: Role
    name: hook-image-awaiter
    jsonPointers:
    - /metadata/annotations
    - /metadata/labels
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: hook-image-awaiter
    jsonPointers:
    - /metadata/annotations
    - /metadata/labels
