apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: "${REPO_URL}"
    targetRevision: "${REVISION}"
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/volumeName
    - /spec/resources/requests/storage
    - /spec/storageClassName
    - /spec/accessModes
    - /spec/volumeMode
    - /metadata/annotations
    - /metadata/labels
  - group: ""
    kind: PersistentVolume
    jsonPointers:
    - /spec/claimRef/resourceVersion
    - /spec/claimRef/uid
    - /spec/claimRef/name
    - /spec/claimRef/namespace
    - /metadata/annotations
    - /metadata/labels
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionWebhook
    jsonPointers:
    - /webhooks
    - /metadata/annotations
    - /metadata/labels
  - group: admissionregistration.k8s.io
    kind: MutatingAdmissionWebhook
    jsonPointers:
    - /webhooks
    - /metadata/annotations
    - /metadata/labels
  - group: ""
    kind: Secret
    name: kube-prometheus-stack-admission
    jsonPointers:
    - /data
    - /metadata/annotations
    - /metadata/labels
