apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: "${REPO_URL}"
    targetRevision: "${REVISION}"
    path: charts/monitoring-crds
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
