apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-crds
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: ml-dev
    server: https://kubernetes.default.svc
  source:
    repoURL: "${REPO_URL}"
    targetRevision: "${REVISION}"
    path: charts/ray-crds
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
    - /metadata/annotations
    - /metadata/labels
