apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: ml-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/shreysatpathy/microPlat.git
    targetRevision: HEAD
    path: charts/ray-operator
    helm:
      values: values.yaml  # optional overrides
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - Replace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
