apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy
  template:
    metadata:
      labels:
        component: proxy
    spec:
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | indent 6 }}
      containers:
      - name: proxy
        image: "{{ .Values.proxy.chp.image.name }}:{{ .Values.proxy.chp.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
