image:
  repository: rayproject/ray
  tag: 2.9.0-py311
  pullPolicy: IfNotPresent

spec:
  rayVersion: "2.9.0"
  headGroupSpec:
    serviceType: LoadBalancer
    rayStartParams: 
      dashboard-host: 0.0.0.0
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.9.0-py311
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 512Mi
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 2
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.9.0-py311
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 512Mi
