image:
  repository: rayproject/ray
  tag: nightly-py311-cpu
  pullPolicy: Always

spec:
  rayVersion: "2.47.0"
  headGroupSpec:
    serviceType: LoadBalancer
    rayStartParams: 
      dashboard-host: 0.0.0.0
    template:
      spec:
        containers:
          - name: ray-head
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 512Mi
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 2
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 512Mi
