image:
  repository: rayproject/ray
  tag: 2.47.0-py311-cpu
  pullPolicy: Always

spec:
  rayVersion: "2.47.0"
  headGroupSpec:
    serviceType: LoadBalancer
    rayStartParams: 
      dashboard-host: 0.0.0.0
      metrics-export-port: "8080"
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"
        labels:
          ray.io/node-type: head
          app.kubernetes.io/name: ray-cluster
          app.kubernetes.io/component: head
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.48.0-py312-cpu
            env:
              - name: RAY_GRAFANA_HOST
                value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
              - name: RAY_GRAFANA_IFRAME_HOST
                value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
              - name: RAY_PROMETHEUS_HOST
                value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
              - name: RAY_PROMETHEUS_NAME
                value: "prometheus"
              - name: RAY_GRAFANA_ORG_ID
                value: "1"
            ports:
              - containerPort: 8080
                name: metrics
                protocol: TCP
              - containerPort: 8265
                name: dashboard
                protocol: TCP
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 512Mi
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 1
      rayStartParams:
        metrics-export-port: "8080"
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
          labels:
            ray.io/node-type: worker
            app.kubernetes.io/name: ray-cluster
            app.kubernetes.io/component: worker
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:2.48.0-py312-cpu
              env:
                - name: RAY_GRAFANA_HOST
                  value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
                - name: RAY_GRAFANA_IFRAME_HOST
                  value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
                - name: RAY_PROMETHEUS_HOST
                  value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
                - name: RAY_PROMETHEUS_NAME
                  value: "prometheus"
                - name: RAY_GRAFANA_ORG_ID
                  value: "1"
              ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
              resources:
                limits:
                  cpu: 2
                  memory: 4Gi
                requests:
                  cpu: 500m
                  memory: 512Mi
