{
 "title": "Train Dashboard",
 "tags": [ "rayVersion:2.47.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "label_values(ray_train_worker_group_start_total_time_s{}, SessionName)"
    }
   },
   {
    "name": "TrainRunName",
    "query": {
     "query": "label_values(ray_train_worker_group_start_total_time_s{}, ray_train_run_name)"
    }
   },
   {
    "name": "TrainRunId",
    "query": {
     "query": "label_values(ray_train_worker_group_start_total_time_s{}, ray_train_run_id)"
    }
   },
   {
    "name": "TrainWorkerWorldRank",
    "query": {
     "query": "label_values(ray_train_report_total_blocked_time_s{}, ray_train_worker_world_rank)"
    }
   },
   {
    "name": "TrainWorkerActorId",
    "query": {
     "query": "label_values(ray_train_report_total_blocked_time_s{}, ray_train_worker_actor_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Checkpoint Report Time",
   "type": "graph",
   "description": "Time taken to report a checkpoint to storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_train_report_total_blocked_time_s{ray_train_worker_world_rank=~'$TrainWorkerWorldRank', ray_train_worker_actor_id=~'$TrainWorkerActorId', SessionName=~\"$SessionName\",ray_train_run_name=~\"$TrainRunName\",ray_train_run_id=~\"$TrainRunId\",}) by (ray_train_run_name, ray_train_worker_world_rank, ray_train_worker_actor_id)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, World Rank: {{ray_train_worker_world_rank}}"
    }
   ]
  },
  {
   "title": "Train Controller Operation Time",
   "type": "graph",
   "description": "Time taken by the controller to perform various operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_train_worker_group_start_total_time_s{SessionName=~\"$SessionName\",ray_train_run_name=~\"$TrainRunName\",ray_train_run_id=~\"$TrainRunId\",}) by (ray_train_run_name)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, Worker Group Start Time"
    },
    {
     "expr": "sum(ray_train_worker_group_shutdown_total_time_s{SessionName=~\"$SessionName\",ray_train_run_name=~\"$TrainRunName\",ray_train_run_id=~\"$TrainRunId\",}) by (ray_train_run_name)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, Worker Group Shutdown Time"
    }
   ]
  },
  {
   "title": "Train Controller State",
   "type": "graph",
   "description": "State of the train controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    {}
   ],
   "targets": [
    {
     "expr": "sum(ray_train_controller_state{SessionName=~\"$SessionName\",ray_train_run_name=~\"$TrainRunName\",ray_train_run_id=~\"$TrainRunId\",}) by (ray_train_run_name, ray_train_controller_state)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, Controller State: {{ray_train_controller_state}}"
    }
   ]
  }
 ]
}