apiVersion: v2
name: jupyterhub
description: JupyterHub Helm chart for ML Platform
type: application
version: 0.1.0
appVersion: "5.0.0"
dependencies:
  - name: jupyterhub
    version: 4.2.0
    repository: https://jupyterhub.github.io/helm-chart/
    condition: jupyterhub.enabled
