apiVersion: v2
name: jupyterhub
description: Multi-user Jupyter installation
type: application
version: 4.2.0
appVersion: 5.3.0
kubeVersion: '>=1.28.0-0'
home: https://z2jh.jupyter.org
icon: https://hub.jupyter.org/helm-chart/images/hublogo.svg
sources:
  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s
maintainers:
  - name: ML Platform Team
