apiVersion: v2
name: jupyterhub-platform
description: Wrapper chart that pulls the official JupyterHub Helm chart and applies opinionated defaults for the ML platform.

# Chart type
type: application

# This chart’s own version (arbitrary – bump when you change *this* wrapper chart)
version: 0.1.0

# The version of the upstream application (for info only)
appVersion: "3.2.1"

dependencies:
  - name: jupyterhub
    version: "3.2.1"  # pick a stable version from https://jupyterhub.github.io/helm-chart/
    repository: "https://jupyterhub.github.io/helm-chart/"
