# Default values for jupyterhub-platform wrapper chart.

proxy:
  secretToken: "REPLACE_ME_WITH_HELM_GENERATED"
  service:
    type: ClusterIP

singleuser:
  image:
    name: ghcr.io/${REGISTRY_OWNER}/ml-platform-notebook
    tag: "latest"
    pullPolicy: IfNotPresent
  storage:
    type: pvc
    capacity: 10Gi
    dynamic:
      storageClass: standard # swap for your StorageClass
  defaultUrl: "/lab"
  extraEnv:
    RAY_ADDRESS: "ray://ray-head:10001"

# Disable hooks to prevent RBAC conflicts
prePuller:
  enabled: false
  hook:
    enabled: false
  continuous:
    enabled: false

hub:
  image:
    name: quay.io/jupyterhub/k8s-hub
    tag: "4.2.0"
  config:
    Authenticator:
      admin_users:
        - admin
      admin_access: true
    JupyterHub:
      admin_access: true
  db:
    pvc:
      storageClassName: standard

# Allow OAuth or dummy auth later
auth:
  type: dummy
  dummy:
    password: "mlplatform"

rbac:
  create: true
