imagePullSecrets: []

hub:
  baseUrl: "/"
  image:
    name: quay.io/jupyterhub/k8s-hub
    tag: "4.2.0"
    pullPolicy: IfNotPresent

proxy:
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: "5.0.1"
  service:
    type: ClusterIP  # or LoadBalancer, depending on your setup

singleuser:
  image:
    name: quay.io/jupyterhub/k8s-singleuser-sample
    tag: "set-by-chartpress"
    pullPolicy: IfNotPresent
  defaultUrl: "/lab"
  storage:
    type: dynamic  # Use "static" if you manually manage PVCs
    homeMountPath: /home/jovyan
    capacity: 10Gi
    dynamic:
      storageClass: standard  # Replace with your actual storage class

ingress:
  enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

custom: {}

cull:
  enabled: false

debug:
  enabled: false

rbac:
  create: false

global:
  safeToShowValues: true
