imagePullSecrets: []

hub:
  baseUrl: "/"
  image:
    name: jupyterhub/jupyterhub
    tag: "4.2.0"
    pullPolicy: IfNotPresent

proxy:
  secretToken: null
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: "latest"

singleuser:
  image:
    name: jupyter/base-notebook
    tag: "latest"
    pullPolicy: IfNotPresent
  defaultUrl: "/lab"
  storage:
    type: dynamic  # Use "static" if you manually manage PVCs
    homeMountPath: /home/jovyan
    capacity: 10Gi
    dynamic:
      storageClass: standard  # Replace with your actual storage class

ingress:
  enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

custom: {}

cull:
  enabled: false

debug:
  enabled: false

rbac:
  create: false

global:
  safeToShowValues: true
