imagePullSecrets: []

# No imagePullSecret creation
imagePullSecret:
  create: false

hub:
  baseUrl: "/"
  image:
    name: jupyterhub/jupyterhub
    tag: 4.2.0
    pullPolicy: IfNotPresent
    pullSecrets: []
  cookieSecret: null

proxy:
  secretToken: null
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: latest
    # No HTTPS, no TLS
    service:
      type: ClusterIP
  service:
    type: ClusterIP

singleuser:
  image:
    name: jupyter/base-notebook
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []
  defaultUrl: "/lab"
  storage:
    type: none

ingress:
  enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

custom: {}
cull:
  enabled: false
debug:
  enabled: false
rbac:
  create: false
global:
  safeToShowValues: true
