jupyterhub:
  enabled: true
  hub:
    config:
      JupyterHub:
        authenticator_class: dummy
  
  singleuser:
    image:
      # This will be built from docker/notebook/Dockerfile
      name: microplat/notebook
      tag: latest
    cmd: ["jupyterhub-singleuser"]
    extraEnv:
      RAY_ADDRESS: "ray://ray-cluster-head-svc.ml-dev.svc.cluster.local:10001"
    storage:
      type: dynamic
      capacity: 5Gi
      extraVolumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
      extraVolumeMounts:
        - name: shared-data
          mountPath: /home/jovyan/shared
    profileList:
      - display_name: "Default: CPU"
        description: "Default profile with CPU resources"
        default: true
        kubespawner_override:
          cpu_limit: 2
          cpu_guarantee: 0.5
          mem_limit: "4G"
          mem_guarantee: "1G"
      - display_name: "Medium: More CPU & Memory"
        description: "More CPU and memory for larger workloads"
        kubespawner_override:
          cpu_limit: 4
          cpu_guarantee: 1
          mem_limit: "8G"
          mem_guarantee: "2G"
    
  proxy:
    service:
      type: ClusterIP
  
  ingress:
    enabled: false

  # Resource settings
  scheduling:
    userScheduler:
      enabled: false
    userPlaceholder:
      enabled: false
    podPriority:
      enabled: false
