# Minimal JupyterHub configuration for GitOps with ArgoCD
imagePullSecrets: []

hub:
  config:
    JupyterHub:
      admin_access: true
      authenticator_class: dummy
      port: 8000
      tornado_settings:
        headers:
          Content-Security-Policy: "frame-ancestors 'self'"
  extraConfig:
    compatibility: |
      c.Spawner.environment = {
          'JUPYTERHUB_SINGLEUSER_APP': 'notebook.notebookapp.NotebookApp'
      }
  image:
    name: quay.io/jupyterhub/k8s-hub
    tag: "4.2.0"
  service:
    type: ClusterIP
  # Required by schema
  baseUrl: /

proxy:
  # Generate with: openssl rand -hex 32
  secretToken: "f89ddee5ba10f2268fcefcd4e353235c1cdbab1f72ea183362f6ba1a22f6d700"
  service:
    type: ClusterIP
  chp:
    image:
      name: quay.io/jupyterhub/configurable-http-proxy
      tag: "4.6.3"

singleuser:
  image:
    name: quay.io/jupyterhub/k8s-singleuser-sample
    tag: "4.2.0"
  cmd: ["jupyterhub-singleuser"]
  storage:
    type: dynamic
    capacity: 1Gi
    dynamic:
      storageClass: standard
    # Required by schema
    homeMountPath: /home/jovyan
  memory:
    guarantee: 512M
    limit: 1G

scheduling:
  userScheduler:
    enabled: false  # Simplify deployment for minimal setup
    # Required by schema even when disabled
    logLevel: 4
    plugins:
      score:
        disabled: []
        enabled: []
    pluginConfig: []
  userPlaceholder:
    enabled: false

prePuller:
  hook:
    enabled: false  # Simplify deployment
  continuous:
    enabled: false

# Required by schema
ingress:
  enabled: false
  
# Required by schema
custom: {}

# Required by schema
cull:
  enabled: true
  timeout: 3600
  every: 600

debug:
  enabled: false

rbac:
  create: true
  
# Required by schema
global:
  safeToShowValues: false
