apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-prometheus-stack.fullname" . }}-ray-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    app: ray-cluster
spec:
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - default
    - ml-dev
    - ml-prod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-prometheus-stack.fullname" . }}-ray-workers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    app: ray-workers
spec:
  selector:
    matchLabels:
      ray.io/node-type: worker
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - default
    - ml-dev
    - ml-prod
