apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-pvc
  labels:
    app.kubernetes.io/name: filestore
    app.kubernetes.io/component: shared-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: filestore-csi
  volumeName: filestore-pv
