# Kubernetes Service Accounts with Workload Identity annotations
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-hub
  namespace: jupyterhub
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-jupyterhub@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/component: hub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-user
  namespace: jupyterhub
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-jupyterhub@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/component: user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-head
  namespace: ray-system
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-ray@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: ray-cluster
    app.kubernetes.io/component: head
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-worker
  namespace: ray-system
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-ray@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: ray-cluster
    app.kubernetes.io/component: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlflow
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-mlflow@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: tracking-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-monitoring@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-monitoring@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-monitoring@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: alerting
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: "PROJECT_ID-argocd@PROJECT_ID.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: server
