name: build-and-push-images

on:
  push:
    branches: [main]
    paths:
      - "docker/**"
      - "charts/**/values.yaml"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - notebook
          - trainer
          - serve
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ matrix.image }}
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/ml-platform-${{ matrix.image }}:latest

      - name: Update Helm values (skip on PRs)
        if: github.event_name == 'push'
        run: |
          IMAGE_TAG=$(date +%s)
          yq -i ".image.tag = \"$IMAGE_TAG\"" charts/${{ matrix.image == 'notebook' && 'jupyterhub' || matrix.image }}/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: bump ${{ matrix.image }} image tag $IMAGE_TAG" || echo "No changes"
          git push origin HEAD:main
