{{- if .Values.mlflow.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mlflow.serviceAccount.name }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.mlflow.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
